# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/litdjango',
                'doc_host': 'https://aaronsgithub.github.io',
                'git_url': 'https://github.com/aaronsgithub/litdjango',
                'lib_path': 'litdjango'},
  'syms': { 'litdjango.cli': { 'litdjango.cli.LitManagementUtility': ('cli.html#litmanagementutility', 'litdjango/cli.py'),
                               'litdjango.cli.LitManagementUtility.__init__': ( 'cli.html#litmanagementutility.__init__',
                                                                                'litdjango/cli.py'),
                               'litdjango.cli.LitManagementUtility.fetch_command': ( 'cli.html#litmanagementutility.fetch_command',
                                                                                     'litdjango/cli.py'),
                               'litdjango.cli.StartApp': ('cli.html#startapp', 'litdjango/cli.py'),
                               'litdjango.cli.StartProject': ('cli.html#startproject', 'litdjango/cli.py'),
                               'litdjango.cli.cli': ('cli.html#cli', 'litdjango/cli.py')}}}
