# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/utils.ipynb.

# %% auto 0
__all__ = ['LITDJANGO_ROOT', 'print_notebook_contents']

# %% ../nbs/utils.ipynb 2
import json
from pathlib import Path

from nbdev.config import get_config

# %% ../nbs/utils.ipynb 3
cfg = get_config()

def get_litdjango_root():
    try:
        LITDJANGO_ROOT = Path(__file__).parent.parent
    except NameError as e:
        if "get_ipython" in globals():
            LITDJANGO_ROOT = cfg.config_path
        else:
            raise e
    return LITDJANGO_ROOT

# %% ../nbs/utils.ipynb 4
LITDJANGO_ROOT = get_litdjango_root()

# %% ../nbs/utils.ipynb 5
def print_notebook_contents(contents):
    """Useful for printing notebook contents to stdout"""
    data = json.loads(contents)
    
    for n, cell in enumerate(data['cells']):
        print(
            f"\n"
             "# -----------------------------\n"
            f"# cell no:{n}\n"
            f"# cell type:{cell['cell_type']}\n"
             "# -----------------------------"
        )
        for line in cell['source']:
            print(line, end='')
