# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../../nbs/demos/djangotutorial/config/wsgi.ipynb.

# %% auto 0
__all__ = []

# %% ../../../../nbs/demos/djangotutorial/config/wsgi.ipynb 3
import os

from django.core.wsgi import get_wsgi_application
